[frontend]
172.31.34.114

[catalogue]
172.31.6.75

[user]
172.31.6.76

[cart]
172.31.6.77



; group of groups
[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

[local:vars]
COURSE = "Ansible for the Test"
DURATION = "150 HRS"
TRAINER = "SivaKumar"

